config/routes.rb
Rails.application.routes.draw do
  root "posts#index"

  resources :posts do
    resources :comments, only: [:new, :create]
  end

  get "/users/:id" => "users#show", as: :user
  patch "/users/:id" => "users#update"

  get   "/signup" => "registrations#new"
  post  "/signup" => "registrations#create"

  get   "/signout" => "authentication#destroy"

  get   "/signin" => "authentication#new"
  post  "/signin" => "authentication#create"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates :description, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :comments
  has_many :posts


  validates :username, :email, presence: true, uniqueness: true

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    User.find_by(id: session[:user_id])
  end

  private
  def authenticate_user
    redirect_to(signin_path) unless current_user
  end
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  def destroy
    session.clear
    redirect_to root_path, notice: "User signed out successfully"
  end

  def new
    @user = User.new
  end

  def create
    @user = User.find_by_email(params[:email])

    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path, notice: "User signed in successfully"
    else
      redirect_to signin_path, alert:"Username / password combination is invalid"
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user, only: [:new, :create]

  def new
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to @post, notice: "Comment created succesfully"
    else
      redirect_to new_comment_post(@post), alert: "Comments cannot be blank"
    end
  end


  private
    def comment_params
      params.require(:comment).permit(:description)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user, only: [:new, :create, :edit, :update, :destroy]
  before_action :ownership_control, only: [:edit, :update, :destroy]

  def index
    @posts = Post.all.order(updated_at: :desc)
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to @post, notice: "Post created succesfully"
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post, notice: "Post updated succesfully"
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path, notice: "Post deleted succesfully"
  end

  private
    def post_params
      params.require(:post).permit(:title, :description)
    end

    def ownership_control
      @post = Post.find_by(id: params[:id], user_id: current_user)
      if @post.nil? && !current_user.is_moderator
        redirect_to root_path, alert: "That post does not belong to you!"
      end
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "User created succefully."
    else
      render :new
    end
  end

  private
    def user_params
      params.require(:user).permit(
        :username,
        :email,
        :password,
        :password_confirmation
      )

    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize_user_admin, only: [:edit, :update, :destroy]

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user, notice: "User updated succesfully"
    else
      render :show
    end
  end

  private
    def user_params
      params.require(:user).permit(:is_moderator)
    end

    def authorize_user_admin
      @user = User.find(params[:id])
      redirect_to @user unless current_user.is_admin
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authentication/new.html.erb
<div class="col-sm-offset-2 col-sm-8">
  <h3>Sign In</h3>
  <hr>

  <%= form_tag signin_path do %>
    <div class="form-group">
      <%= email_field_tag :email, nil, {placeholder:"email", class:"form-control"} %>
    </div>

    <div class="form-group">
      <%= password_field_tag :password, nil, {placeholder:"password", class:"form-control"} %>
    </div>

    <div class="form-group pull-right">
      <%= submit_tag "Sign In", class:"btn btn-primary", id:"user-login-action" %>
      <%= link_to "cancel", root_path, class:"btn btn-default" %>
    </div>
  <% end %>
</div>

app/views/comments/new.html.erb
<div class="col-sm-offset-2 col-sm-8">
  <h3>Add Comment to <%= @post.title %></h3>
  <hr>

  <% if @comment.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

    <ul>
      <% @comment.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

<%= form_for [@post, @comment] do |f| %>
  <div class="form-group">
    <%= f.text_area :description, rows: 5, placeholder:"Comment", class:"form-control" %>
  </div>
  <div class="form-group pull-right">
    <%= f.submit id:"comment-create-action", class:"btn btn-primary" %>
    <%= link_to "cancel", @post, class:"btn btn-default" %>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% if notice %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-danger" role="alert">
    <%= alert %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="nav navbar navbar-default">
  <div class="container-fluid">
    <% if current_user %>
      <div class="nav navbar-nav">
        <div class="navbar-text">
          Signed in as <%= link_to current_user.username, user_path(current_user), id:"user-show-action" %> |
          <%= link_to "Sign Out", signout_path, id:"signout-action" %>
        </div>
      </div>
    <% else %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Sign Up", signup_path, class:"navbar-link", id:"signup-action" %></li>
        <li><%= link_to "Sign In", signin_path, class:"navbar-link", id:"signin-action" %></li>
      </ul>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render "layouts/navbar" %>

    <div class="jumbotron">
      <h1><%= link_to "g", root_path, class: "navbar-brand" %> | Reddit </h1>
    </div>

    <div class="main-panel">
      <%= render "layouts/flash" %>

      <%= yield %>
    </div>
  </div>

</body>
</html>

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

  <ul>
    <% @post.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<%= form_for @post do |f| %>
  <div class="form-group">
    <%= f.text_field :title, placeholder:"Title", class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.text_area :description, rows: 5, placeholder:"Description", class:"form-control" %>
  </div>

  <div class="form-group pull-right">
    <%= f.submit id:"post-create-action", class:"btn btn-primary" %>

    <%= (link_to "cancel", root_path, class:"btn btn-default") if params[:action] == "new" %>
    <%= (link_to "cancel", @post, class:"btn btn-default") if params[:action] == "edit" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <% unless post.comments.count.zero? %>
      <span class="badge pull-right"><%= post.comments.count %></span>
    <% end %>
    <strong>
      <%= link_to post.title, post_path(post), id:"post-show-action" %>
    </strong>
  </div>
  <div class="panel-footer">
    <div class="text-muted">
      <em>
        <%= "posted #{time_ago_in_words(post.updated_at)} ago - by" %>
        <%= link_to post.user.username, post.user %>
      </em>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="col-sm-offset-2 col-sm-8">
  <h3>Editing <%= @post.title %></h3>
  <hr>

<%= render "form" %>
</div

app/views/posts/index.html.erb
<h3>Recent Posts</h3>
<hr>
<%= render @posts %>

<%= link_to "Post something", new_post_path, id:"post-new-action" %>

app/views/posts/new.html.erb
<div class="col-sm-offset-2 col-sm-8">
  <h3>Create a post</h3>
  <hr>

<%= render "form" %>
</div>

app/views/posts/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4 class="panel-title">
      <%= @post.title %>
      <div class="pull-right">
        <small>
          <%= "Posted by " %>
          <%= link_to @post.user.username, @post.user %>
          <%= "- #{@post.updated_at.strftime("%b %e, %Y")}" %>
        </small>
      </div>
    </h4>
  </div>
  <div class="panel-body">
    <%= raw sanitize(simple_format(@post.description), :tags => %w(br p) ) %>
    <hr>
    <% @comments.each do |comment| %>
      <div class="panel panel-default">
        <div class="panel-body">
          <%= comment.description %>
          <div class="pull-right">
            comment by
            <strong><%= link_to comment.user.username, comment.user %></strong>
            <div class="text-muted text-right">
              <em><%= comment.created_at.strftime("%b %e, %Y") %></em>
            </div>
          </div>
        </div>
      </div>
    <% end %>

<%= link_to "Back", posts_path %> |
<%= link_to "Add Comment", new_post_comment_path(@post), id:"comment-new-action" %>
<% if current_user && (current_user.id == @post.user_id || current_user.is_moderator) %>
| <%= link_to "Edit Post", edit_post_path(@post), id:"post-edit-action" %> |
<%= link_to "Delete Post", post_path(@post), id:"post-delete-action", method: :delete, data:{confirm: "Are you sure?"} %>
<% end %>
  </div>
</div>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

  <ul>
    <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<%= form_for @user do |f| %>
  <%= f.label :is_moderator %>
  <%= f.check_box :is_moderator %>

  <%= f.submit id:"user-update-submit"%>
<% end %>

app/views/users/show.html.erb
<h3><%= @user.username %></h3>
<% if @user.is_moderator %>
  <strong>Moderator</strong>
<% end %>
<hr>

<dl class="dl-horizontal">
  <dt>Member Since:</dt>
  <dd> <%= @user.created_at.strftime("%b %e, %Y") %> </dd>

  <% if @user.posts.exists? %>
    <dt>Number of Posts:</dt>
    <dd> <%= @user.posts.count %> </dd>

    <dt>Last Post:</dt>
    <dd><%= ("#{time_ago_in_words(@user.posts.last.updated_at)} ago") if @user.posts %></dd>
  <% end %>

  <% if @user.comments.exists? %>
    <dt>Number of Comments:</dt>
    <dd><%= @user.comments.count %></dd>

    <dt>Last Comment:</dt>
    <dd><%= ("#{time_ago_in_words(@user.comments.last.updated_at)} ago") if @user.comments %></dd>
  <% end %>
</dl>

<%= render "form" %>

<% if @user.posts.exists? %>
  <strong>Posts:</strong>
  <ul class="list-unstyled">
  <% @user.posts.order(updated_at: :desc).each do |post| %>
    <li>
      <%= link_to post.title, post %>
    </li>
  <% end %>
  </ul>
  <hr>
<% end %>
<%= link_to "Back", root_path %>